#!/hint/bash
# shellcheck disable=2034

#
# makepkg.conf
#

BUILDENV=(!distcc color !ccache check sign)

OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto !autodeps)

## For building AUR packages
#-- Packager: name/email of the person or organization building packages
PACKAGER="AUR <Built on $HOSTNAME>"
