#!/hint/bash
# shellcheck disable=2034

#
# makepkg-cal.conf
#

## For building custom packages

OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto !autodeps)

#-- Packager: name/email of the person or organization building packages
PACKAGER="Cal <cal@underkill>"

Include=$XDG_CONFIG_HOME/pacman/common.conf
