#!/hint/bash
# shellcheck disable=2034

#
# makepkg.conf
#

## For building AUR packages

OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)

#-- Packager: name/email of the person or organization building packages
PACKAGER="AUR <Built on $HOST>"

Include=$XDG_CONFIG_HOME/pacman/common.conf
