#! /bin/bash
# From this:

# bar="▁▂▃▄▅▆▇█"
# dict="s/;//g;"

# # creating "dictionary" to replace char with bar
# i=0
# while [ $i -lt ${#bar} ]
# do
#     dict="${dict}s/$i/${bar:$i:1}/g;"
#     i=$((i=i+1))
# done

# # make sure to clean pipe
# pipe="/tmp/cava.fifo"
# if [ -p $pipe ]; then
#     unlink $pipe
# fi
# mkfifo $pipe

# # write cava config
# config_file="/tmp/waybar_cava_config"
# echo "
# [general]
# bars = 10
# [output]
# method = raw
# raw_target = $pipe
# data_format = ascii
# ascii_max_range = 7
# " > $config_file

# # run cava in the background
# cava -p $config_file &

# # reading data from fifo
# while read -r cmd; do
#     echo $cmd | sed $dict
# done < $pipe

printf "[general]\nframerate=60\nbars = 21\n[output]\nmethod = raw\nraw_target = /dev/stdout\ndata_format = ascii\nascii_max_range = 8\n"\
| cava -p /dev/stdin | sed -u 's/;//g;s/0/ /g;s/1/▁/g;s/2/▂/g;s/3/▃/g;s/4/▄/g;s/5/▅/g;s/6/▆/g;s/7/▇/g;s/8/█/g; '