#!/usr/bin/env bash

# function clamp {
#   min=$1
#   max=$2
#   val=$3
#   python -c "print(max($min, min($val, $max)))"
# }

spaces (){
  WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .name | tostring, value: .windows}) | from_entries')
  # WORKSPACE_COUNT=$(hyprctl workspaces -j | jq '[(.[]["id"] | if . < 0 then empty end)] | sort | .[-1]+1')
  # LIMIT_COUNT=$(clamp 1 10 $(($WORKSPACE_COUNT)))
  seq 1 10 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  spaces
done