#!/usr/bin/bash
# output: ["window_class", "window_title"]
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | 
sed -u -e s/'::*'/'::'/g -e s/'>>'/':::'/ -e s/','/':::'/ - | 
stdbuf -o0 awk -F ':::' '/^activewindow:::/{ print "[\""$2"\", \""$3"\"]" }'
# if window title or class has more than 2 colons in a row (ie ':::') they will be replaced with just 2 colons ('::')