#!/bin/sh
hyprctl activewindow -j | jq --raw-output .class # Provides a little hint to if eww is reloading corectly
# will output title if title is shorter than the first arg in chars, else class
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 awk -F '>>|,' '/^activewindow>>/{if (length($3) > '$1') print $2; else print $3}'