#! /usr/bin/env bash

findmnt --real -o TARGET,SOURCE,FSTYPE,LABEL -J |
 jq -c '.[] | [.. | {mount: .target? // empty, dev: .source?, fs: .fstype?} + (if .label? then {label: .label} else null end)] | 
    map(del(select(.mount == "/boot")) // empty)' |
 sed 's/fuseblk/ntfs/g' |
 jq -c '[.[] | . + (. | 
   if .mount == "/" then {icon:"󰣇", remote:false, sort:0} 
   elif .mount == "/mnt/c" then {icon:"", remote:false, sort:1, name:"C:/"} 
   elif .label == "KOBOeReader" then {icon:"", remote:false, sort:6, name:"Kobo"} 
   elif .fs == "cifs" then {icon:"󰡰", remote:true, sort:9} 
   else {icon:"", remote:false, sort:7} end) + 
   ( . | if (.dev | test("^\/\/archives.shrew-gray.ts.net")) then {name:"Archives"} end)] | 
   sort_by(.sort)' 