#! /usr/bin/bash
CURRENT_SINK=$(pactl get-default-sink)

pactl --format='json' list sinks |
jq -c --arg current "$CURRENT_SINK" '[.[] | {(.name | tostring): {"description", "state", "mute"} + 
    (.properties | {type: (.["device.form_factor"]), 
        icon: (if .["device.form_factor"] == "headset" then "󰋋" 
            elif .["device.form_factor"] == "internal" then "󰓃"
            else null end)})}] |
    {default: $current} + add(.[])' |
sed 's/Built-in Audio Analog Stereo/Internal Speakers/g'