#!/bin/sh

MUTED=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $3}')

if [ -n "$MUTED" ]; then
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}' | jq -c '[., true]'
    exit
else
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}' | jq -c '[., false]'
fi